# Generated by Django 3.2 on 2024-09-16 15:05

from django.db import migrations, models
import djongo.models.fields


class Migration(migrations.Migration):

    initial = True

    dependencies = [
    ]

    operations = [
        migrations.CreateModel(
            name='OrderList',
            fields=[
                ('_id', djongo.models.fields.ObjectIdField(auto_created=True, primary_key=True, serialize=False)),
                ('party_name', models.CharField(default='NA', max_length=100)),
                ('party_details', models.JSONField(default=dict)),
                ('date', models.DateField(auto_now=True)),
                ('orderList', models.JSONField(default=dict)),
                ('total_price', models.DecimalField(decimal_places=2, default=0, max_digits=10)),
            ],
        ),
        migrations.CreateModel(
            name='Parties',
            fields=[
                ('_id', djongo.models.fields.ObjectIdField(auto_created=True, primary_key=True, serialize=False)),
                ('party_name', models.CharField(default='NA', max_length=100)),
                ('mobile', models.CharField(default='NA', max_length=10)),
                ('gst_number', models.CharField(default='NA', max_length=100, unique=True)),
                ('address', models.CharField(default='NA', max_length=100)),
            ],
        ),
        migrations.CreateModel(
            name='Product',
            fields=[
                ('id', models.BigAutoField(auto_created=True, primary_key=True, serialize=False, verbose_name='ID')),
                ('design_no', models.CharField(max_length=100, unique=True)),
                ('total_set', models.IntegerField()),
                ('color', models.CharField(max_length=50)),
                ('price', models.DecimalField(decimal_places=2, max_digits=10)),
                ('image', models.ImageField(upload_to='product_images')),
            ],
        ),
        migrations.CreateModel(
            name='PurchaseList',
            fields=[
                ('_id', djongo.models.fields.ObjectIdField(auto_created=True, primary_key=True, serialize=False)),
                ('party_name', models.CharField(default='NA', max_length=100)),
                ('party_details', models.JSONField(default=dict)),
                ('date', models.DateField(auto_now=True)),
                ('purchaseList', models.JSONField(default=dict)),
                ('total_price', models.DecimalField(decimal_places=2, default=0, max_digits=10)),
            ],
        ),
    ]
