# Generated by Django 4.1.13 on 2024-08-27 06:59

from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('stock', '0002_alter_product_image'),
    ]

    operations = [
        migrations.AlterField(
            model_name='product',
            name='design_no',
            field=models.CharField(max_length=100, unique=True),
        ),
    ]
