# Generated by Django 4.1.13 on 2024-09-07 08:57

from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('stock', '0006_parties'),
    ]

    operations = [
        migrations.AddField(
            model_name='parties',
            name='address',
            field=models.CharField(default='NA', max_length=100),
        ),
        migrations.AddField(
            model_name='parties',
            name='gst_number',
            field=models.CharField(default='NA', max_length=100, unique=True),
        ),
        migrations.AddField(
            model_name='parties',
            name='mobile',
            field=models.CharField(default='NA', max_length=10),
        ),
        migrations.AddField(
            model_name='parties',
            name='party_name',
            field=models.CharField(default='NA', max_length=100),
        ),
    ]
