# Generated by Django 4.1.13 on 2024-09-13 08:25

from django.db import migrations


class Migration(migrations.Migration):

    dependencies = [
        ('stock', '0007_parties_address_parties_gst_number_parties_mobile_and_more'),
    ]

    operations = [
        migrations.RenameField(
            model_name='product',
            old_name='total_pieces',
            new_name='total_set',
        ),
        migrations.RemoveField(
            model_name='product',
            name='pieces_set',
        ),
    ]
