# Generated by Django 3.2 on 2024-09-15 07:29

from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('stock', '0008_rename_total_pieces_product_total_set_and_more'),
    ]

    operations = [
        migrations.CreateModel(
            name='OrderList',
            fields=[
                ('id', models.BigAutoField(auto_created=True, primary_key=True, serialize=False, verbose_name='ID')),
                ('party_name', models.CharField(default='NA', max_length=100)),
                ('party_details', models.JSONField(default=dict)),
                ('date', models.DateField(auto_now=True)),
                ('orderList', models.JSONField(default=dict)),
            ],
        ),
        migrations.DeleteModel(
            name='Order',
        ),
    ]
