# Generated by Django 3.2 on 2024-09-15 07:40

from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('stock', '0009_auto_20240915_1259'),
    ]

    operations = [
        migrations.AddField(
            model_name='orderlist',
            name='total_price',
            field=models.DecimalField(decimal_places=2, default=0, max_digits=10),
        ),
    ]
